version: "3"
services:
  web:
    build: ./flask-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  mongo:
    image: mongo
    restart: always
    ports:
      - "27012:27012"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
networks:
  app-network:
    driver: bridge
volumes:
  flask-data:
  mongo-data:
